g++.exe -c -fexceptions -I . -idirafter rs  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\rtdb.o rtdb.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\io_b64.o rs/io_b64.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\io_comm.o rs/io_comm.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\io_compress.o rs/io_compress.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\io_expand.o rs/io_expand.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\io_ezf.o rs/io_ezf.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\io_file.o rs/io_file.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\io_inet.o rs/io_inet.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\io_fifo.o rs/io_fifo.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\io_list.o rs/io_list.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\io_memory.o rs/io_memory.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\io_open.o rs/io_open.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\io_pipe.o rs/io_pipe.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\io_print.o rs/io_print.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\io_stream.o rs/io_stream.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\io_xml.o rs/io_xml.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\io_zip.o rs/io_zip.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\sy_alloc.o rs/sy_alloc.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\sy_char.o rs/sy_char.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\sy_crc.o rs/sy_crc.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\sy_except.o rs/sy_except.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\sy_file.o rs/sy_file.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\sy_form.o rs/sy_form.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\sy_int32.o rs/sy_int32.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\sy_list.o rs/sy_list.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\sy_mswin.o rs/sy_mswin.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\sy_param.o rs/sy_param.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\sy_sort.o rs/sy_sort.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\sy_string.o rs/sy_string.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\sy_strlist.o rs/sy_strlist.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\sy_time.o rs/sy_time.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\sy_url.o rs/sy_url.cpp
g++.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\sy_worm.o rs/sy_worm.cpp
gcc.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\adler32.o zlib/adler32.c
gcc.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\trees.o zlib/trees.c
gcc.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\zutil.o zlib/zutil.c
gcc.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\deflate.o zlib/deflate.c
gcc.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\infblock.o zlib/infblock.c
gcc.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\infcodes.o zlib/infcodes.c
gcc.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\inffast.o zlib/inffast.c
gcc.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\inflate.o zlib/inflate.c
gcc.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\inftrees.o zlib/inftrees.c
gcc.exe -c -fexceptions -I .  -D NO_NOTES_MAIL -D NO_CMC_MAIL -D NO_DBF_ENCRYPTION -D XP_WIN -D _Windows   -O2 -Os   -oobj\infutil.o zlib/infutil.c
g++.exe -s  -o rtdb.exe -mconsole -mwindows -mole obj\rtdb.o obj\io_b64.o obj\io_comm.o obj\io_compress.o obj\io_expand.o obj\io_ezf.o obj\io_file.o obj\io_inet.o obj\io_fifo.o obj\io_list.o obj\io_memory.o obj\io_open.o obj\io_pipe.o obj\io_print.o obj\io_stream.o obj\io_xml.o obj\io_zip.o obj\sy_alloc.o obj\sy_char.o obj\sy_crc.o obj\sy_except.o obj\sy_file.o obj\sy_form.o obj\sy_int32.o obj\sy_list.o obj\sy_mswin.o obj\sy_param.o obj\sy_sort.o obj\sy_string.o obj\sy_strlist.o obj\sy_time.o obj\sy_url.o obj\sy_worm.o obj\adler32.o obj\trees.o obj\zutil.o obj\deflate.o obj\infblock.o obj\infcodes.o obj\inffast.o obj\inflate.o obj\inftrees.o obj\infutil.o   -lole32 -lws2_32 -lstdc++ -lodbc32 -loleaut32 -lmapi32 -lcomdlg32 -luuid   
